wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.22.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1761921183
    t:
      1:
      - 1
      - 50
      2:
      - 1
      - 50
      3:
      - 2
      - 4
      - 13
      - 16
      - 42
      4: 3.10.18
      5: 0.22.2
      13: linux-x86_64
    e:
      fmrjan9d8gujcirltxvmmxox22w6fs6b:
        os: Linux-6.14.0-32-generic-x86_64-with-glibc2.39
        python: CPython 3.10.18
        started_at: '2025-10-31T14:33:02.619206Z'
        args:
        - data.split_index=1
        program: /media/wsqlab/data/ctp_file/EEG_encoder/main_2o.py
        code_path: main_2o.py
        code_path_local: main_2o.py
        git:
          remote_url: https://github.com/qazwsx2323ppp/EEG_encoder.git
          commit: 4f313aff519433060aa10f762cd1bb6e2103b5ef
        root: /media/wsqlab/data/ctp_file/EEG_encoder
        host: wsqlab-SYS-420GP-TNR
        executable: /media/wsqlab/data/miniforge/envs/eeg2it_clone/bin/python
        cpu_count: 56
        cpu_count_logical: 112
        gpu_type: NVIDIA TITAN RTX
        gpu_count: 8
        disk:
          /:
            total: '1966736678912'
            used: '768963747840'
        memory:
          total: '270046150656'
        gpu_nvidia:
        - name: NVIDIA TITAN RTX
          memory_total: '25769803776'
          cuda_cores: 4608
          architecture: Turing
          uuid: GPU-2246cfce-4ef1-99fd-bd13-275c1821e575
        - name: NVIDIA TITAN RTX
          memory_total: '25769803776'
          cuda_cores: 4608
          architecture: Turing
          uuid: GPU-01f06e16-b8ab-747e-c5ee-abc085b9073e
        - name: NVIDIA TITAN RTX
          memory_total: '25769803776'
          cuda_cores: 4608
          architecture: Turing
          uuid: GPU-d1801db1-2f77-4034-a578-5b4096bd2688
        - name: NVIDIA TITAN RTX
          memory_total: '25769803776'
          cuda_cores: 4608
          architecture: Turing
          uuid: GPU-963d3440-dfe0-be7d-7fc2-69cc6d7acf00
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-7ccd39e8-3932-ab45-5ad8-94f3568d3375
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-0bf9de64-4a37-acc3-1ec6-9a7caf252331
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-1188d4da-6f38-1ee9-9fe2-4d1db223301d
        - name: NVIDIA GeForce RTX 2080 Ti
          memory_total: '11811160064'
          cuda_cores: 4352
          architecture: Turing
          uuid: GPU-cb7665eb-9227-5fdd-6064-76b3edde2597
        cuda_version: '13.0'
        writer_id: fmrjan9d8gujcirltxvmmxox22w6fs6b
wandb:
  desc: null
  value:
    project: EEG_Decoupling
    entity: null
    name: eeg_triplet_train
data:
  desc: null
  value:
    root: /media/wsqlab/data/ctp_file/EEG_encoder
    split_index: 1
    eeg_path: /media/wsqlab/data/ctp_file/EEG_encoder/data/EEG_data/eeg_55_95_std.pth
    image_vec_path: /media/wsqlab/data/ctp_file/EEG_encoder/data/image_vectors.npy
    text_vec_path: /media/wsqlab/data/ctp_file/EEG_encoder/data/text_vectors.npy
    splits_path: /media/wsqlab/data/ctp_file/EEG_encoder/data/EEG_data/block_splits_by_image_all.pth
training:
  desc: null
  value:
    epochs: 100
    batch_size: 64
    learning_rate: 0.0001
    num_workers: 4
    device: cuda
    alpha: 0.5
    temperature: 0.1
model:
  desc: null
  value:
    model_name: eeg_encoder
    n_linear_layers: 1
    channel_merge: linear
    n_heads: 8
    embedding_dim: 512
    n_channels: 128
    n_samples: 440
    encoder_name: braindecode_shallow
    n_filters_time: 40
    filter_time_length: 25
    n_filters_spat: 40
    pool_time_length: 75
    pool_time_stride: 15
    drop_prob: 0.5
