# configs/triplet_config.yaml

# 1. Hydra 默认设置
defaults:
  - _self_
  - override hydra/launcher: slurm # 如果在集群上运行，否则可以注释掉

# 2. WandB 日志 (推荐使用)
wandb:
  project: "EEG_Decoupling"
  entity: null # 替换为您的 wandb 用户名
  name: "eeg_triplet_train"

# 3. 数据路径
# !! 必须修改这里的路径，指向您本地的数据 !!
data:
    root: ${hydra:runtime.cwd}
    split_index: 0  # 0~5 可选
    eeg_path: ${data.root}/data/EEG_data/eeg_55_95_std.pth
    image_vec_path: ${data.root}/data/image_vectors_aligned.npy
    text_vec_path: ${data.root}/data/text_vectors_aligned.npy
    splits_path: ${data.root}/data/EEG_data/block_splits_by_image_all.pth

# 4. 训练参数
training:
  epochs: 100
  #data11.8_1
  #batch_size: 64
  batch_size: 64
  learning_rate: 0.0001
  num_workers: 4
  device: "cuda" # 'cuda' or 'cpu'
  #data11.8_1 早停，若在10个epoch中loss没有就停止
  patience: 10
  min_delta: 0.01       # <-- 新增：损失改善小于 0.01 不算“改善”
  #权重衰减 data11.8_0
  weight_decay: 0.1

  # 损失函数权重 (alpha * loss_img + (1-alpha) * loss_txt)
  alpha: 0.5

  # InfoNCE 损失函数的温度参数
  temperature: 0.2

# 5. EEG 编码器模型参数
#    这些参数来自 EEG-CLIP 仓库，您可以直接使用
model:
  model_name: 'eeg_moe'  # 更改名称以区分
  
  # [新增] Checkpoint 路径 (请修改为你存放 .pth 的真实路径)
  pretrained_path: '${data.root}/temp/checkpoint.pth'

  # EEG 编码器参数
  n_linear_layers: 1
  channel_merge: 'linear' # 'linear' or 'attention'
  n_heads: 8

  # 确保这个维度与您的 image/text 向量维度一致
  # e.g., 512 for 'clip-vit-base-patch32'
  embedding_dim: 512

  # EEG 信号参数 (必须与数据匹配)
  n_channels: 128
  n_samples: 440

  # 编码器主干网络 (来自 clip_models.py)
  encoder_name: 'braindecode_shallow' # 'braindecode_shallow' 或 'braindecode_deep'

# --- 新增：基于拓扑的分区专家配置 ---
  # 请使用 Python 列表格式填入对应的通道索引 (0-127)
  # 示例：枕叶(O系列, PO系列) -> 视觉; 颞叶(T系列)/额叶(F系列) -> 语义
  moe_config:
    # # [语义专家 Visual Expert]
    # # 对应大脑后部 (顶叶、枕叶)，负责处理图像特征
    # # 选取索引 64 到 127 (共64个通道)
    # #暂时换一下 12.8.20
    # visual_indices: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]
    
    # # [视觉专家 Semantic Expert]
    # # 对应大脑前部 (额叶、颞叶)，负责处理语义理解和概念
    # # 选取索引 0 到 63 (共64个通道)
    # semantic_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]

    # [Fusion专家] 使用所有 128 通道 (无需配置，代码自动处理)
    router_type: "global_channel_attention"


  # 卷积层参数 data11.8_1
  #n_filters_time: 40
  n_filters_time: 20
  filter_time_length: 25
  #n_filters_spat: 40
  n_filters_spat: 20
  pool_time_length: 75
  pool_time_stride: 15
  drop_prob: 0.6

# 6. Hydra 运行设置
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}